- name: create a directory in /home/saber
  file:
    path: /home/saber/dir1
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: [create_dir]

- name: create a file in /home/saber/dir1
  file:
    path: /home/saber/dir1/file1
    state: touch
    owner: root
    group: root
    mode: 0644
  tags: [create_file]

- name: Delete file in /home/saber/dir1
  file:
    path: /home/saber/dir1/file1
    state: absent
  tags: [delete_file]




